// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH-wWHGX6Ql2ipFdxL-8-ntfb7zbK4GNE',
    appId: '1:838637845394:web:a9d2b75f016c70a5e91f4b',
    messagingSenderId: '838637845394',
    projectId: 'proyecto-practica-ia-1b24f',
    authDomain: 'proyecto-practica-ia-1b24f.firebaseapp.com',
    storageBucket: 'proyecto-practica-ia-1b24f.firebasestorage.app',
    measurementId: 'G-7YKFCLW01N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJxlt-pJrdoPO78WzXGIbIMrz8KaKYVCw',
    appId: '1:838637845394:android:84b1cf785c8ca845e91f4b',
    messagingSenderId: '838637845394',
    projectId: 'proyecto-practica-ia-1b24f',
    storageBucket: 'proyecto-practica-ia-1b24f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTcA1pdT_33zuv2KdJCwQiCc_Uf_-AIGE',
    appId: '1:838637845394:ios:3186ebe372562714e91f4b',
    messagingSenderId: '838637845394',
    projectId: 'proyecto-practica-ia-1b24f',
    storageBucket: 'proyecto-practica-ia-1b24f.firebasestorage.app',
    iosBundleId: 'com.example.proyectoPracticaIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTcA1pdT_33zuv2KdJCwQiCc_Uf_-AIGE',
    appId: '1:838637845394:ios:3186ebe372562714e91f4b',
    messagingSenderId: '838637845394',
    projectId: 'proyecto-practica-ia-1b24f',
    storageBucket: 'proyecto-practica-ia-1b24f.firebasestorage.app',
    iosBundleId: 'com.example.proyectoPracticaIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH-wWHGX6Ql2ipFdxL-8-ntfb7zbK4GNE',
    appId: '1:838637845394:web:bc32826bfbe156e4e91f4b',
    messagingSenderId: '838637845394',
    projectId: 'proyecto-practica-ia-1b24f',
    authDomain: 'proyecto-practica-ia-1b24f.firebaseapp.com',
    storageBucket: 'proyecto-practica-ia-1b24f.firebasestorage.app',
    measurementId: 'G-2R2V683D53',
  );
}
